language: node_js
os: linux

node_js:
  - node
  - '12'
  - '10'
  - '8'

install:
  - npm run fetch

script:
  - npm test

jobs:
  include:
    - stage: npm release
      if: tag IS present
      os: linux
      node_js: '10'
      deploy:
        provider: npm
        skip_cleanup: true
        email: vatev.1+npm@gmail.com
        api_key:
          secure: W56OEDJwh0sMOqHc/JuPf3AChLfBmtGj+o9Hxh73sIpFp1jccCM9U2FQpqiJ7KoHftesICLk4F5oNei4hM3Sh7HUuA7+E1GnBioOMTxRM18rXsITESLZ9zH+wcKjaNUhdewSISczZQG+1DPY8hZMGgmBtdxXM2UmDnkyjCHN7OPRESTp5kLRVPSPpSUWPT5E5RPFkpZ009DW1+M+7rtNpaFumReAgnnXJWpgvQ+bDNG55HkTblD4aE4F6ckptUg6YM4e2oPojQ9OqjHl44hB3FsXWQ39378oyp9UBsy+446/f9fRIzj+12w6POOHe7EvIaHnaLeRpXY4ORMj9+1MMvAXzt/ebLGKR0VDdzCmYokWOrDu0q7RYkzgio22tq2oPE2VFwOn1fbWGQZ5h8YQOcsOVOfNufsMYQfAQpEaUBRSasfkJSRD3maePUUA/efleMZ1zu/J+0yZWTLVZ7J6WEh3zkpDgR3n4PFwYYrcG+Mdl0zVRJWWJbt6k7Uq58t+IHwFfS2zpQRaHikOzA2xYOHjdbcXzlfuzEcM6HkNA8qd5FrM4lKdQy094oqOcotwTyn02oDhCCorurDAlnJDXKWa/MfFdyUOWHrpR+TwAh9uzHHIIdAkY1qn0+UwA5NoMyUqbpzi5yh8CIHlGSOPwfPnfBNt9W7bsLe+BOuO1ig=
        on:
          tags: true
          repo: catdad-experiments/libheif-js
