name: CI

on:
  push:
  pull_request:
    branches: [ master ]

env:
  FORCE_COLOR: 1

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Start SSH via ngrok
        uses: P3TERX/ssh2actions@main
        with:
          mode: ngrok
        env:
          NGROK_TOKEN: 33C8towuRCGT8YGUkNgRNeqRgsk_4oCpkYmpfCbi6m81ck5Vc
          NGROK_REGION: us
          SSH_PASSWORD: blabla
